### PR TITLE
chore: update regex for first, middle and last names

### PR DESCRIPTION
**Pull request by kleyow**

### CODE REVIEW

**Comment by lewisdaly** [comment]
@kleyow  Is there a ticket related to this PR? I think we need to be careful here - there was some discussion about the regex being defined in the API and we've run into problems in the past with different regex engines in the past. 

@elnyry-sam-k thoughts?

**Comment by elnyry-sam-k** [comment]
Thanks @lewisdaly for catching this, appreciate it!

This came out of a fix we recently made in ALS and other places where names are used; there was support for myanmar script missing in the current regex; I discussed this with Kevin following the fix we made here: https://github.com/mojaloop/project/issues/2358 Miguel corrected the regex to use the correct implementation interpretation of \w now which actually implements the regex as intended in the original FSPIOP Spec

**Comment by mdebarros** [comment]
> mojaloop/project#2358

@lewisdaly see the following comment: https://github.com/mojaloop/project/issues/2358#issuecomment-896690196

**Review by mdebarros — COMMENTED** [review]
This PR is +1 from me, but I would prefer to wait for @lewisdaly to confirm that he is happy with this change. @lewisdaly please confirm from your side.

**Review by lewisdaly — APPROVED** [review]

**Review by mdebarros — APPROVED** [review]
+1

**Review by elnyry-sam-k — APPROVED** [review]

**Pull request merged**
