### PR TITLE
Update to work using `swagger-cli` and `openapi-backend`

### PR DESCRIPTION
**Pull request by stevenwjy**
Hi, here is my draft PR to propose some changes that could be added to the `api-snippets` to make it work using [`swagger-cli`](https://github.com/APIDevTools/swagger-cli) and [`openapi-backend`](https://github.com/anttiviljami/openapi-backend).

First of all, sorry for combining these changes into a single PR. This is because my current work on the `pisp-demo-server` is using this branch as a dependency. If it is important to break the changes into two separate PRs, I can cherry-pick my commits and split them into two.

## Why `swagger-cli`?

Here are the main reasons I decided to try finding other alternatives for `multi-file-swagger` (which is currently used in this repository):
1. Poor dependency resolution.
   - As could be seen [here](https://github.com/mohsen1/multi-file-swagger-example/blob/master/resolve.js), all the library does is to call `json-refs` to resolve all the `$ref` symbols. 
   - One problem with this is that all the reference paths are based on our path when executing the command, not the file it is written. Hence, when writing a library like this, it is just too much of a trouble since we couldn't predict how the people who use this library wants to execute the command. 
   - With the way it is currently written, if i want to reference a file that has references to other files, I need to figure out all of the dependencies so I can put it in my schema. However, I think that is not an ideal way to do things especially as the code base for this api snippets get bigger. I personally got confused just to keep encountering errors on which schemas I had not included in my open api specification file.
2. No validation check
    - If the reference fails, then `multi-swagger-file` will basically do nothing and just let it be there. Then, we will notice our mistakes when testing the result using a swagger editor. However, as a user, I want to know directly if I try to reference a non-existent path so I can quickly locate the errors without having the hassle of using swagger editor. 
    - There is also no checking in `multi-swagger-file` if let's say it produces an invalid open api specification. Meanwhile, as a user, I also want to know right away if my open api specification is invalid as it will cause future problems. 

And, yeah, so far I guess `swagger-cli` has managed to resolve those problems. It uses the path of the file where the `$ref` is written and there's a command to validate the resulting specification file. I have made all (if I don't miss anything) the changes necessary to align with the way `swagger-cli` resolve `$ref`.

## What's with the `openapi-backend`?

There's a problem with how `openapi-backend` perform schema validation, which is using [`openapi-schema-validation`](https://www.npmjs.com/package/openapi-schema-validation)(deprecated, but works similar with its replacement [`openapi-schema-validator`](https://github.com/kogosoftwarellc/open-api/tree/master/packages/openapi-schema-validator)). It performs more strict validation than `swagger-cli validate ...`, which does not allow sibling elements of `$ref`.

According to the [official documentation](https://swagger.io/docs/specification/using-ref/), sibling elements of `$ref` will just be ignored, which I believe why `swagger-cli` does not complain about it. However, `openapi-backend` won't allow that and there seems so be some errors displayed by swagger editor as well if we have that. 

Hence, to make it work with `openapi-backend`, I removed all the sibling elements of `$ref` that exist in this `api-snippets`. Currently the descriptions were just removed but the examples were added to the base schema. I think this will need some updates on how to use the original description for some properties. The main problem I guess is because for `properties` in a schema, we need to either reference to another file (and take their description) or write everything by ourselves. Previously, the `api-snippets` try to reference to another file and overwrite the description, but it is not allowed by the validator so I just removed the description.

Also, I added a folder for `headers` as `responses` could not use the same format of headers listed in `parameters`.

## Extra

In this draft PR, I also added a template for responses that return 200 and 202, since they are commonly used in Mojaloop. It seems to work with `swagger-cli validate ...`, but again `openapi-backend` and swagger editor complain about it. Hence, I guess I can just remove it if it couldn't be used in the end. 

Hope this could help to improve the current api-snippets library! Thank you!

### CODE REVIEW

**Comment by kleyow** [comment]
`audit:check` and `audit:resolve` to fix vulnerability check.
Can you update the readme with instructions of how another service maintainer would use the new tools?
As well as removing multi-file-swagger from the `scripts` in package.json`

Looks good so far!

**Comment by stevenwjy** [comment]
Okay, resolved the issues with `audit:check`. I have also updated the README file about how to use this snippet with `swagger-cli`.

Sorry for taking some time to update this, I have been trying to test that the updated api-snippets could work as expected in the `pisp-demo-server` repo. It looks good so far and I think it's ready for review :)

**Comment by stevenwjy** [comment]
Is it fine to merge this PR? Or perhaps need review from someone else? @kleyow

**Comment by stevenwjy** [comment]
Btw, just realized I forgot to remove the `template` folder. It was added to simplify the code since most of the APIs in mojaloop have similar response set (either `200` or `202` + a lot of other errors). While it seems to have no problem with `swagger-cli`, the validator in `openapi-backend` complains for some errors that I couldn't understand and hence I stopped using the template.

**Comment by kleyow** [comment]
You can go ahead and merge. Be sure to use squash and merge

**Comment by stevenwjy** [comment]
Okay, got it, thank you!

**Pull request merged**
