### PR TITLE
chore: add account related snippets

### PR DESCRIPTION
**Pull request by kleyow**

### CODE REVIEW

**Review by lewisdaly — APPROVED** [review]
Looks good - my only concern is that we should figure out some proper structure for versioning this stuff here, since some of these are not in the FSPIOP-API `v1.0` or even `v1.1`

**Comment by kleyow** [comment]
Confused. Can you clarify?

Versioning the thirdparty snippets? Or versioning thirdparty snippets that are based on the FSPIOP spec like `Party` and `PartiesTypeIDPutResponse`?

**Comment by kleyow** [comment]
Merging for now since I need this for other work.

**Comment by lewisdaly** [comment]
> Or versioning thirdparty snippets that are based on the FSPIOP spec like `Party` and `PartiesTypeIDPutResponse`?

This one - it's ok for now, but just something we need to have on the radar.

**Pull request merged**
