### PR TITLE
feat: 1923 common dto for v1.0

### PR DESCRIPTION
**Pull request by eoln**
- typescript definitions for v1.0 api-snippets
- some initial documentation of how to use DTO

### CODE REVIEW

**Comment by elnyry-sam-k** [comment]
@eoln version bump, v11.1.0?

**Comment by eoln** [comment]
@elnyry-sam-k I believe the version should be automatically bumped by Ci/Cd, let me check...

**Comment by eoln** [comment]
we are using the [standard-version ](https://www.npmjs.com/package/standard-version)which will do a proper bump version in CI/CD

**Review by elnyry-sam-k — APPROVED** [review]
looking good!

**Pull request merged**
