### PR TITLE
chore: add U2F to AuthenticationType in v1.1

### PR DESCRIPTION
**Pull request by sridharvoruganti**

### CODE REVIEW

**Review by eoln — APPROVED** [review]
lgtm

**Comment by kleyow** [comment]
Hmm you should really be defining U2F in v1.1 since it's not in the specification. Is this related to the duplicate importing of `AuthenticationType`?

**Comment by sridharvoruganti** [comment]
@kleyow  In sdk-scheme-adapter inbound definition, you used '/authorizations/{ID}':
    $ref: '../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/paths/authorizations_ID.yaml'
so to support incoming put response validation, added 'U2F' to AuthenticationType.yaml.

**Comment by kleyow** [comment]
Hmm...oh yea I'll need to redefine the paths too for the changes to propagate up...

I'll have to mull this over to figure out how to iron this out. No problem, continue on since this is dependent on the ticket you're working on.

**Pull request merged**
